name: Client

on:
  push:
    branches: [ main ]
  pull_request:
    bracnhes: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Run client
        working-directory: client
        run: |
          npm install
          npm start &
          npm run test:unit
        env:
          CI: true
          API_URI: http://localhost:9000
